In [ ]:
Practica numpy 

In [ ]:
Lista tradicional vs arreglos numpy

In [1]:
lista = [2,4.3,'Hola']
lista[2]

'Hola'

In [3]:
matriz =[[1,2,3],
         [4,5,6],
         [7,8,9]]
print(matriz[1][2])

6


In [1]:
import numpy as np
a = np.array([2,56,7,8])
print(a)

[ 2 56  7  8]


In [13]:
#secuencia = np.arange(3,15,2)
secuencia = np.linspace(2, 10, 15)
secuencia

array([ 2.        ,  2.57142857,  3.14285714,  3.71428571,  4.28571429,
        4.85714286,  5.42857143,  6.        ,  6.57142857,  7.14285714,
        7.71428571,  8.28571429,  8.85714286,  9.42857143, 10.        ])

In [6]:
#ceros = np.zeros((7, 5))
#ceros
#unos = np.ones(5)
#unos
full = np.full((2,5), 5)
full

NameError: name 'np' is not defined

In [22]:
base = np.linspace(2,6,4)
print(np.full_like(base,np.pi))

[3.14159265 3.14159265 3.14159265 3.14159265]


In [30]:
azar = np.random.rand(2,3)
azar

array([[0.89241016, 0.16035783, 0.95538688],
       [0.71765541, 0.09229164, 0.87540816]])